# Generated by Django 5.1 on 2024-11-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WrappedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('wrapped_data', models.JSONField()),
            ],
        ),
    ]
