# Generated by Django 5.1.3 on 2024-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0008_wrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrapcounter',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='playlists',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='recently_played',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='saved_albums',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='top_artists',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='top_genres',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='top_track_popularity_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='top_track_popularity_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wrapcounter',
            name='top_tracks',
            field=models.JSONField(default=list),
        ),
    ]
