# Generated by Django 5.1.3 on 2024-11-30 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0008_userwrappedhistory_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwrappedhistory',
            name='profile_data',
        ),
    ]
