# Generated by Django 5.1.3 on 2024-12-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wrapped', '0010_remove_wrapcounter_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrappedhistory',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
